### ISSUE TITLE
ImportError: cannot import name 'sysconfig'

### ISSUE THREAD

**Issue by ayamshanov** [plesk/ubuntu18to20#12]
**Describe the bug**
It is impossible to start the script on Ubuntu18, the execution stops right after the running with the next error...
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

# plesk version
Product version: Plesk Obsidian 18.0.66.0
     OS version: Ubuntu 18.04 x86_64
     Build date: 2024/12/06 22:00
       Revision: 5cf42fe3a278aacd47be41a4d1515951b2c425b0

# wget https://github.com/plesk/ubuntu18to20/releases/download/v2.1.2/ubuntu18to20-2.1.2.zip
# unzip ubuntu18to20-2.1.2.zip
# chmod 755 ubuntu18to20

# ./ubuntu18to20 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./ubuntu18to20/__main__.py", line 25, in <module>
  File "/root/ubuntu18to20/.bootstrap/_pex/pex_bootstrapper.py", line 97, in bootstrap_pex
  File "/root/ubuntu18to20/.bootstrap/_pex/pex.py", line 10, in <module>
ImportError: cannot import name 'sysconfig'
```

**Feedback archive**
*Please attach a feedback archive to the bug report.*
```# ubuntu18to20 --prepare-feedback
# ./ubuntu18to20 --prepare-feedback
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./ubuntu18to20/__main__.py", line 25, in <module>
  File "/root/ubuntu18to20/.bootstrap/_pex/pex_bootstrapper.py", line 97, in bootstrap_pex
  File "/root/ubuntu18to20/.bootstrap/_pex/pex.py", line 10, in <module>
ImportError: cannot import name 'sysconfig'```

**Comment by SandakovMM** [comment]
There was a problem with the tool created by GitHub Actions. I have released a new version with Ubuntu18to20 built manually by me, so it should now function properly. Please use [release v2.2.0](https://github.com/plesk/ubuntu18to20/releases/tag/v2.2.0)
